apiVersion: v1
kind: Service
metadata:
  name: autodeploy24
  namespace: namespace-workflow-1708345026832
spec:
  type: LoadBalancer
  selector:
    app: autodeploy24
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000